CurseWords:
  - fuck
  - shit
  - pussy
  - dick
  - nigga
  - nigra
  - nigger
  - anus
  - ass
  - asshole
  - twat
  - penis
  - vagina
  - hypixel
  - cubecraft
  - hive
  - arse
  - bitch
  - bastard
  - bollocks
  - child-fucker
  - christ on a bike
  - christ on a cracker
  - cunt
  - damn
  - goddamn
  - godsdamn
  - hell
  - holy shit
  - motherfucker
  - shit ass
  - shitass
  - son of a bitch
  - son of a motherless goat
  - son of a whore
  - sweet Jesus
